name: chef_ai
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  go_router: ^13.2.0

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_vertexai: ^1.0.3
  firebase_auth: ^5.3.3
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
